 version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/clojure
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: clojure
      POSTGRES_PASSWORD: clojure
      POSTGRES_DB: clojure
    ports:
      - "5432:5432"
