name: Docker Compose CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose -y

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo service postgresql start
        sudo -u postgres psql -c "CREATE USER clojure WITH PASSWORD 'clojure';"
        sudo -u postgres psql -c "CREATE DATABASE clojure OWNER clojure;"

    - name: Build and run Docker Compose services
      run: docker-compose up -d --build

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until pg_isready -h localhost -U clojure; do
          sleep 5
        done

    - name: Check Docker Compose services
      run: docker-compose ps

    - name: Display logs
      run: docker-compose logs app

    - name: Run tests
      run: docker-compose exec app lein test

    - name: Shut down Docker Compose services
      run: docker-compose down
