name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: clojure
          POSTGRES_PASSWORD: clojure
          POSTGRES_DB: clojure
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U clojure"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose -y

    - name: Build and run Docker Compose services
      run: docker-compose up -d --build

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for postgres service to be ready..."
        until docker-compose exec db pg_isready -U clojure; do
          sleep 5
        done

    - name: Run tests
      run: docker-compose exec app lein test

    - name: Shut down Docker Compose services
      run: docker-compose down
